# -*- coding: utf-8 -*-
"""1.a. Rule-Based Expert System for Disease Diagnosis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KI2KoKpKG9S_jXvBn_2Wef2ZWArl7Y-v
"""

!pip install frozendict==1.2
!pip install experta
import collections
import collections.abc
collections.Mapping = collections.abc.Mapping
collections.MutableMapping = collections.abc.MutableMapping
collections.Iterable = collections.abc.Iterable

from experta import *

class Symptom(Fact):
    pass

class DiagnosisSystem(KnowledgeEngine):
    @Rule(Symptom(name="fever"))
    @Rule(Symptom(name="cough"))
    def flu(self):
        print("Diagnosis: You may have the Flu.")

    @Rule(Symptom(name="headache"))
    @Rule(Symptom(name="nausea"))
    def migraine(self):
        print("Diagnosis: You may have a Migraine.")

    @Rule(Symptom(name="chest_pain"))
    @Rule(Symptom(name="shortness_of_breath"))
    def heart_issue(self):
        print("Diagnosis: You may have a Heart-related issue. Please consult a doctor immediately.")

engine = DiagnosisSystem()
engine.reset()

# Ask user for symptoms
symptoms = input("Enter your symptoms separated by commas: ").split(",")

# Feed symptoms to the system
for s in symptoms:
    engine.declare(Symptom(name=s.strip()))

engine.run()